### ISSUE TITLE
uncrustify has been patched for QNX and version 0.68 does not include patch

### ISSUE THREAD

**Issue by asobhy-qnx** [ament/uncrustify_vendor#11]
uncrustify has been patched for QNX and version 0.68 does not include patch.

need to use master branch commit 25d8cab6434f21aee3f96227e3bec5d282a6d883

**Comment by asobhy-qnx** [comment]
@dirk-thomas please let me know how you would like to move forward with this issue

**Comment by dirk-thomas** [comment]
There isn't a released version containing the patch yet. But this package could pull the archive from e.g. the commit hash of the current head. Please create a pull request updating the URL and MD5 and including a comment why it is necessary.

**Comment by asobhy-qnx** [comment]
@dirk-thomas since uncrustify is a linter then it needs to be running on a development system only, there is no need to cross compile it because no one will be developing code on a QNX system, is my understanding correct?

**Comment by dirk-thomas** [comment]
> since uncrustify is a linter then it needs to be running on a development system only, there is no need to cross compile it because no one will be developing code on a QNX system, is my understanding correct?

Correct.

**Comment by asobhy-qnx** [comment]
uncrustify is a host tool and does not need to be cross compiled for QNX as a result I will mark this issue as resolved
